server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306
    username: root
    password: 123456
    hikari:
      # 连接池名
      pool-name: DateHikariCP
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接最大存活时间 10分钟
      idle-timeout: 600000
      # 最大连接数
      maximum-pool-size: 20
      # 从连接池返回的连接的自动提交
      auto-commit: true
      # 连接最大存活时间 30分钟（0表示永久存活）
      max-lifetime: 1800000
      # 连接超时时间 30秒
      connection-timeout: 30000
      # 测试连接是否可用的查询语句
      connection-test-query: SELECT 1
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri:

mybatis-plus:
  # Mapper映射文件位置
  mapper-locations: classpath*:/mapper/**/*.xml
  # 配置MyBatis数据返回类型别名（默认是类名）
  type-aliases-package: com.ygq.server.pojo
  configuration:
    # 关闭自动驼峰命名规则映射
    map-underscore-to-camel-case: false

# 日志打印，mapper接口所在的包
logging:
  level:
    com.ygq.server.mapper: debug

jwt:
  # JWT存储的请求头
  tokenHeader: Authorization
  # JWT加解密使用的密钥
  secret: yeb-secret
  # JWT的有效时长
  expiration: 86400
  # JWT负载中拿到开头
  tokenHead: Bearer